FROM oven/bun:1.2.23

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig*.json ./

COPY packages/ ./packages/
COPY apps/pinger/ ./apps/pinger/

RUN bun install

CMD ["bun", "run", "start:pinger"]