FROM oven/bun:1.2.23

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig*.json ./

COPY packages/ ./packages/
COPY apps/api/ ./apps/api/
COPY apps/web/ ./apps/web/
COPY apps/pinger/ ./apps/pinger/

RUN bun install

RUN bun run build

COPY infra/start.sh ./start.sh
RUN chmod +x start.sh

CMD ["./start.sh"]