FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lock ./
COPY tsconfig*.json ./

COPY packages/ ./packages/
COPY apps/pinger/ ./apps/pinger/

RUN bun install

CMD ["bun", "run", "start:pinger"]